### ISSUE TITLE
Specify APIs to manage user groups (create new group, group meta information, etc)

### ISSUE THREAD

**Issue by gr2m** [eHealthAfrica/kazana-account#80]
depends on https://github.com/eHealthAfrica/kazana-account/issues/79, part of https://github.com/eHealthAfrica/kazana/issues/132

  - [ ] extend REST API (http://docs.accountjsonapi.apiary.io/#)
  - [ ] extend client API
  - [ ] extend plugin API
  - [ ] extend Kazana auth strategy / configuration for routes (http://hapijs.com/api#route-options)
